export const SHOW_EMAIL_SING_IN = 'SHOW_EMAIL_SING_IN';
export const SHOW_ENTRANCE = 'SHOW_ENTRANCE';
export const SET_EMAIL = 'SET_EMAIL';
export const SET_PASSWORD = 'SET_PASSWORD';
export const SET_SIGNIN_FAIL_MESSAGE = 'SET_SIGNIN_FAIL_MESSAGE';
